import type { Knex } from 'knex';

/**
 * P1 — DB-level uniqueness for document numbers.
 *
 * Invoice numbers are generated by a row-locked sequence RPC (safe), but there
 * was no UNIQUE constraint as a backstop, and the delivery/challan fallbacks use
 * a racy COUNT(*)+1. A UNIQUE index turns any duplicate (from a fallback path,
 * a bug, or a future non-locked writer) into a hard error instead of silent
 * corruption of the tax-invoice sequence.
 *
 * Partial indexes (WHERE ... IS NOT NULL) so historical NULL/blank numbers do
 * not block the migration. If genuine duplicates already exist the migration
 * fails LOUDLY with the offending rows — de-duplicate, then re-run. This is the
 * intended behaviour: you want to know before enforcing uniqueness.
 */
async function assertNoDuplicates(
  knex: Knex,
  table: string,
  column: string,
): Promise<void> {
  const dupes = await knex.raw(
    `SELECT dealer_id, ${column} AS value, COUNT(*)::int AS n
       FROM ${table}
      WHERE ${column} IS NOT NULL AND ${column} <> ''
      GROUP BY dealer_id, ${column}
     HAVING COUNT(*) > 1
      LIMIT 20`,
  );
  if (dupes.rows?.length) {
    throw new Error(
      `Cannot add UNIQUE(${table}.dealer_id, ${column}) — duplicates exist. ` +
        `De-duplicate these first: ${JSON.stringify(dupes.rows)}`,
    );
  }
}

export async function up(knex: Knex): Promise<void> {
  await assertNoDuplicates(knex, 'sales', 'invoice_number');
  await assertNoDuplicates(knex, 'challans', 'challan_no');
  await assertNoDuplicates(knex, 'deliveries', 'delivery_no');

  await knex.raw(
    `CREATE UNIQUE INDEX IF NOT EXISTS uq_sales_dealer_invoice_number
       ON sales (dealer_id, invoice_number)
       WHERE invoice_number IS NOT NULL AND invoice_number <> ''`,
  );
  await knex.raw(
    `CREATE UNIQUE INDEX IF NOT EXISTS uq_challans_dealer_challan_no
       ON challans (dealer_id, challan_no)
       WHERE challan_no IS NOT NULL AND challan_no <> ''`,
  );
  await knex.raw(
    `CREATE UNIQUE INDEX IF NOT EXISTS uq_deliveries_dealer_delivery_no
       ON deliveries (dealer_id, delivery_no)
       WHERE delivery_no IS NOT NULL AND delivery_no <> ''`,
  );
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw('DROP INDEX IF EXISTS uq_sales_dealer_invoice_number');
  await knex.raw('DROP INDEX IF EXISTS uq_challans_dealer_challan_no');
  await knex.raw('DROP INDEX IF EXISTS uq_deliveries_dealer_delivery_no');
}
